// src/pages/Home/mockData.js

export const mockStudies = [
  {
    id: 1,
    title: "K.K. UI/UX 스터디",
    description: "Slow and steady wins the race!",
    category: "디자인",
    progress: 80,
    members: 12,
    studyCount: 37, // 👩‍💻 참여자 수
    fireCount: 26, // 🔥 응원 수
    heartCount: 14, // 🤍 좋아요 수
  },
  {
    id: 2,
    title: "영문 에세이 첨삭",
    description: "Practice writing with feedback.",
    category: "영어",
    progress: 60,
    members: 7,
    studyCount: 21,
    fireCount: 9,
    heartCount: 5,
  },
  {
    id: 3,
    title: "JavaScript 알고리즘 챌린지",
    description: "Solve coding problems and improve logic.",
    category: "개발",
    progress: 45,
    members: 10,
    studyCount: 42,
    fireCount: 19,
    heartCount: 13,
  },
  {
    id: 4,
    title: "비즈니스 영어 회화",
    description: "Communicate effectively in business.",
    category: "영어",
    progress: 25,
    members: 8,
    studyCount: 18,
    fireCount: 4,
    heartCount: 3,
  },
  {
    id: 5,
    title: "UI 디자인 시스템 구축",
    description: "Design scalable component systems with Figma.",
    category: "디자인",
    progress: 70,
    members: 9,
    studyCount: 35,
    fireCount: 22,
    heartCount: 11,
  },
  {
    id: 6,
    title: "React 초급 스터디",
    description: "Learn React from the basics.",
    category: "개발",
    progress: 40,
    members: 15,
    studyCount: 44,
    fireCount: 18,
    heartCount: 16,
  },
  {
    id: 7,
    title: "창의적 글쓰기",
    description: "Write creative essays with structure.",
    category: "문학",
    progress: 20,
    members: 5,
    studyCount: 11,
    fireCount: 3,
    heartCount: 5,
  },
  {
    id: 8,
    title: "데이터 분석 입문",
    description: "Analyze data using Python and Pandas.",
    category: "데이터",
    progress: 55,
    members: 11,
    studyCount: 30,
    fireCount: 16,
    heartCount: 10,
  },
  {
    id: 9,
    title: "AI 윤리 세미나",
    description: "Discuss ethical issues in artificial intelligence.",
    category: "AI",
    progress: 10,
    members: 6,
    studyCount: 12,
    fireCount: 5,
    heartCount: 2,
  },
  {
    id: 10,
    title: "프론트엔드 면접 대비",
    description: "Prepare for technical interviews and whiteboard coding.",
    category: "개발",
    progress: 65,
    members: 14,
    studyCount: 33,
    fireCount: 20,
    heartCount: 9,
  },
  {
    id: 11,
    title: "디지털 마케팅 전략",
    description: "Learn SEO, SEM, and social media marketing.",
    category: "마케팅",
    progress: 35,
    members: 13,
    studyCount: 22,
    fireCount: 7,
    heartCount: 8,
  },
  {
    id: 12,
    title: "Python 머신러닝 실습",
    description: "Hands-on machine learning with scikit-learn.",
    category: "데이터",
    progress: 50,
    members: 9,
    studyCount: 28,
    fireCount: 12,
    heartCount: 6,
  },
  {
    id: 13,
    title: "영상 편집 마스터클래스",
    description: "Edit like a pro using Premiere Pro and After Effects.",
    category: "영상",
    progress: 75,
    members: 8,
    studyCount: 39,
    fireCount: 17,
    heartCount: 13,
  },
  {
    id: 14,
    title: "AI 서비스 기획",
    description: "Plan and design AI-powered user experiences.",
    category: "AI",
    progress: 30,
    members: 10,
    studyCount: 15,
    fireCount: 8,
    heartCount: 6,
  },
  {
    id: 15,
    title: "음악 프로듀싱 워크샵",
    description: "Create beats and mix songs with modern DAWs.",
    category: "음악",
    progress: 55,
    members: 6,
    studyCount: 20,
    fireCount: 14,
    heartCount: 10,
  },
  {
    id: 16,
    title: "심리학 입문 스터디",
    description: "Understand human behavior and motivation.",
    category: "심리",
    progress: 40,
    members: 7,
    studyCount: 19,
    fireCount: 5,
    heartCount: 7,
  },
  {
    id: 17,
    title: "Node.js 백엔드 스터디",
    description: "Build RESTful APIs with Express and MongoDB.",
    category: "개발",
    progress: 60,
    members: 12,
    studyCount: 41,
    fireCount: 22,
    heartCount: 14,
  },
  {
    id: 18,
    title: "고급 영어 리스닝",
    description: "Practice native-level listening comprehension.",
    category: "영어",
    progress: 20,
    members: 5,
    studyCount: 10,
    fireCount: 3,
    heartCount: 4,
  },
  {
    id: 19,
    title: "UX 리서치 실무",
    description: "Learn user interview and usability testing skills.",
    category: "디자인",
    progress: 75,
    members: 9,
    studyCount: 38,
    fireCount: 25,
    heartCount: 12,
  },
  {
    id: 20,
    title: "데이터 시각화 스터디",
    description: "Build dashboards with D3.js and Tableau.",
    category: "데이터",
    progress: 45,
    members: 10,
    studyCount: 29,
    fireCount: 15,
    heartCount: 9,
  },
];
